export const posts = [
  {
    user: 'Erik',
    statusText: 'På semester i norge! Skön utsikt!',
    imageURL: 'https://fsmedia.imgix.net/84/b9/ea/a2/ba07/4378/845d/c2091d1a9f08/norwayfjord-widejpg.jpeg',
    comments: [{ user: 'Kalle', text: 'Fin bild!' }, { user: 'Oskar', text: 'I approve!' }],
    likes: 12,
  },
  {
    user: 'William',
    statusText: 'Nya pärlan!',
    imageURL: 'https://i.ytimg.com/vi/sPCVmcfRyO8/maxresdefault.jpg',
    comments: [{ user: 'Evelina', text: 'Fräsig tjärra!' }, { user: 'Oskar', text: 'I approve!' }],
    likes: 75,
  },
  {
    user: 'William',
    statusText: 'Grattis Per-Åke på din 80 års dag!',
    imageURL: 'https://drsamtocco.files.wordpress.com/2011/08/dscf5503.jpg',
    comments: [{ user: 'Amilia', text: 'Så jävla snygg!!! Vill du leka lite nakenlekar?' }, { user: 'Sig', text: 'Gammal men stilig!' }, { user: 'Oskar', text: 'Vilken sexbomb!!!' }, { user: 'Per', text: 'Grattis på dig gubben' }, { user: 'Kerstin', text: 'Nästan lika sexig som på din 18 års dag' }],
    likes: 75,
  },
  {
    user: 'Tomas',
    statusText: 'Rekord fångst, hela 9 kilo!',
    imageURL: 'https://www.hooked.no/wp-content/uploads/2017/01/Store-agn-for-stor-fisk-2-550x367.jpg',
    comments: [{ user: 'Pontus', text: 'Vilken baddare!' }, { user: 'Karin', text: 'Ikväll blir det sushi!' }, { user: 'elinwagen', text: 'Shit! Akta så den inte biter dig!!!!' }],
    likes: 89,
  },
  {
    user: 'Peter',
    statusText: 'Solsken, härligt!',
    imageURL: 'https://hjordnara.files.wordpress.com/2012/09/2012-09-06-07-50-303.jpg',
    comments: [],
    likes: 9,
  },
  {
    user: 'Niklas',
    statusText: 'Precis stigit av planet i thailand!',
    imageURL: 'https://netmobius.freetls.fastly.net/images-dmk/dm3.jpg',
    comments: [{ user: 'Daniel', text: 'Ha det så kul!' }, { user: 'Jakob', text: 'Gud vad härligt!' }],
    likes: 28,
  },
  {
    user: 'Orvar',
    statusText: 'Precis införskaffat MC-kort, nu kan jag äntligen ta mig ut på vägen med den här rackaren!',
    imageURL: 'https://migrated.ifokus.se/uploads/2f5/2f5def232838c2abee02026f924e622f/bild3.jpg',
    comments: [{ user: 'Kalle', text: 'Stackars trafikanter, Orvar och 2 hjuls fordon går inte ihop..!' }, { user: 'Oskar', text: 'I approve!' }],
    likes: 19,
  },
  {
    user: 'Johanna',
    statusText: 'Här är min älsklingshäst Tomasson Breeze, han har rullat 7 500 hästmil och är nu till salu. Fungerar felfri och är i gott skick. Ring för mer info! 073 000 00 00',
    imageURL: 'https://migrated.ifokus.se/uploads/13f/13ff0bb5ea386607055ec3927fcde4c6/tappimule.jpg',
    comments: [{ user: 'Kalle', text: 'Jävlar vilken varelse! ' }, { user: 'Erik', text: 'Den ser farlig ut!' }, { user: 'Julia', text: 'Ååh vad söt!' }, { user: 'Cecilia', text: 'Fräsig häst!' }],
    likes: 685,
  },
]


export const users = [
  {
    user: 'Erik',
    followerCount: 87,
    followingCount: 84,
    followers: [
      'Kalle',
      'Oskar',
      'Ylva',
      'Kerstin',
      'Lars',
    ],
    following: [
      'Kalle',
      'Ylva',
      'Kerstin',
      'Lars',
    ],
    posts: posts.filter(post => post.user === 'Erik'),
  },
  {
    user: 'William',
    followerCount: 176,
    followingCount: 82,
    followers: [
      'Kalle',
      'Oskar',
      'Ylva',
      'Kerstin',
      'Lars',
    ],
    following: [
      'Kalle',
      'Ylva',
      'Kerstin',
      'Lars',
    ],
    posts: posts.filter(post => post.user === 'William'),
  },
  {
    user: 'Tomas',
    followerCount: 230,
    followingCount: 139,
    followers: [
      'Kalle',
      'Oskar',
      'Ylva',
      'Kerstin',
      'Lars',
    ],
    following: [
      'Kalle',
      'Ylva',
      'Kerstin',
      'Lars',
    ],
    posts: posts.filter(post => post.user === 'Tomas'),
  },
  {
    user: 'Peter',
    followerCount: 26,
    followingCount: 76,
    followers: [
      'Kalle',
      'Oskar',
      'Ylva',
      'Kerstin',
      'Lars',
    ],
    following: [
      'Kalle',
      'Ylva',
      'Kerstin',
      'Lars',
    ],
    posts: posts.filter(post => post.user === 'Peter'),
  },
  {
    user: 'Niklas',
    followerCount: 87,
    followingCount: 84,
    followers: [
      'Kalle',
      'Oskar',
      'Ylva',
      'Kerstin',
      'Lars',
    ],
    following: [
      'Kalle',
      'Ylva',
      'Kerstin',
      'Lars',
    ],
    posts: posts.filter(post => post.user === 'Niklas'),
  },
  {
    user: 'Orvar',
    followerCount: 87,
    followingCount: 84,
    followers: [
      'Kalle',
      'Oskar',
      'Ylva',
      'Kerstin',
      'Lars',
    ],
    following: [
      'Kalle',
      'Ylva',
      'Kerstin',
      'Lars',
    ],
    posts: posts.filter(post => post.user === 'Orvar'),
  },
  {
    user: 'Johanna',
    followerCount: 8378,
    followingCount: 964,
    followers: [
      'Kalle',
      'Erik',
      'Julia',
      'Cecilia',
      'danimofficial',
      'pitbullofficial',
      'zaralarssonofficial'
    ],
    following: [
      'Kalle',
      'Ylva',
      'Kerstin',
      'Lars',
    ],
    posts: posts.filter(post => post.user === 'Johanna'),
  },
]
